import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";

export interface Student {
  id: string;
  first_name: string;
  last_name: string;
  /** What an AI model sees instead of the name; generated by the database. */
  nickname: string;
  teacher_id: string;
  svp: boolean;
  notes: string;
  interests: string;
  communication_preferences: string;
  learning_styles: string;
  svp_details: string;
}

export function useStudents() {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["students", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("students")
        .select("*")
        .order("last_name", { ascending: true });
      if (error) throw error;
      return data as Student[];
    },
    enabled: !!user,
  });
}

export function useStudent(id: string | undefined) {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["students", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("students")
        .select("*")
        .eq("id", id!)
        .single();
      if (error) throw error;
      return data as Student;
    },
    enabled: !!user && !!id,
  });
}

export function useCreateStudents() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (students: { first_name: string; last_name: string }[]) => {
      const rows = students.map((s) => ({ ...s, teacher_id: user!.id }));
      const { data, error } = await supabase.from("students").insert(rows).select();
      if (error) throw error;
      return data;
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["students"] }),
  });
}

export function useUpdateStudent() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, first_name, last_name, nickname, svp, notes, interests, communication_preferences, learning_styles, svp_details }: {
      id: string;
      first_name: string;
      last_name: string;
      nickname?: string;
      svp?: boolean;
      notes?: string;
      interests?: string;
      communication_preferences?: string;
      learning_styles?: string;
      svp_details?: string;
    }) => {
      const { error } = await supabase
        .from("students")
        .update({
          first_name,
          last_name,
          ...(nickname !== undefined ? { nickname } : {}),
          svp: svp ?? false,
          notes: notes ?? "",
          interests: interests ?? "",
          communication_preferences: communication_preferences ?? "",
          learning_styles: learning_styles ?? "",
          svp_details: svp_details ?? "",
        })
        .eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["students"] });
    },
  });
}

export function useDeleteStudent() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      // Delete related records first
      const { error: psErr } = await supabase.from("proof_students").delete().eq("student_id", id);
      if (psErr) throw psErr;
      const { error: csErr } = await supabase.from("class_students").delete().eq("student_id", id);
      if (csErr) throw csErr;
      const { error: evErr } = await supabase.from("evaluations").delete().eq("student_id", id);
      if (evErr) throw evErr;
      const { error } = await supabase.from("students").delete().eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["students"] });
      queryClient.invalidateQueries({ queryKey: ["class_students"] });
      queryClient.invalidateQueries({ queryKey: ["all_class_students"] });
    },
  });
}

/** A nickname already taken by another of the teacher's pupils. */
export function isDuplicateNickname(error: unknown): boolean {
  const e = error as { code?: string; message?: string } | null;
  return e?.code === "23505" && (e.message ?? "").includes("students_teacher_nickname_key");
}

// Re-export student utilities for backward compatibility during migration
export { getStudentDisplayName, getStudentShortName } from "@/utils/student";
