-- Phase 2 of the new version: the data model around criteria.
--
-- A lesson has one goal, the goal has (up to three) criteria, and every
-- criterion carries a teacher's and a pupil's wording plus a four-step scale
-- J < Č < T < Ú for the pupil. What a pupil has reached is recorded per
-- criterion in `criterion_assessments`, one row per entry, so the history
-- builds itself. Exit tickets and QR self-assessment write into the same table.
--
-- Codes are stored as ASCII: J, C (Č), T, U (Ú). Labels live in
-- src/constants/jctu.ts.

-- =============================================================================
-- 1. Courses (thematic plans) and lessons
-- =============================================================================

alter table public.courses
  add column if not exists school_year text,
  add column if not exists period text,
  add column if not exists source_text text;

-- lessons.course_id already exists (20260329).
alter table public.lessons
  add column if not exists description text not null default '',
  add column if not exists hours numeric,
  add column if not exists month text,
  add column if not exists position int,
  add column if not exists rvp_outcome text,
  add column if not exists materials jsonb not null default '{}'::jsonb;

create index if not exists lessons_course_position_idx on public.lessons (course_id, position);

-- =============================================================================
-- 2. Criteria: teacher and pupil wording, SVP variants, JČTÚ scale, position
-- =============================================================================

alter table public.evaluation_criteria
  add column if not exists teacher_text text,
  add column if not exists pupil_text text,
  add column if not exists svp_variants jsonb not null default '[]'::jsonb,
  add column if not exists scale jsonb,
  add column if not exists position int;

-- A scale, when present, is an object with the four sentences for the pupil.
alter table public.evaluation_criteria drop constraint if exists evaluation_criteria_scale_shape;
alter table public.evaluation_criteria add constraint evaluation_criteria_scale_shape check (
  scale is null
  or (jsonb_typeof(scale) = 'object' and scale ?& array['J', 'C', 'T', 'U'])
);

-- Map an old level name onto the nearest JČTÚ code.
--
-- Old levels were free text taken from the goal's own level list: the default
-- "Začínám / Rozvíjím se / Ovládám", or names the AI proposed such as
-- "Výborně ovládl/a" or "S pomocí zvládl/a". Words decide first; the order is
-- deliberate ("nezvládl" before "zvládl", "s pomocí" and "dobře" before the
-- top level). Only a name no word recognises falls back to its position in the
-- goal's list, read from lowest to highest.
create or replace function public.legacy_level_to_jctu(p_level text, p_levels text[])
returns text
language plpgsql
immutable
as $$
declare
  idx int;
  n int;
  codes text[] := array['J', 'C', 'T', 'U'];
begin
  if p_level is null or btrim(p_level) = '' then
    return null;
  end if;
  if p_level ~* '(začín|nezvl|neosvoj|ještě|zatím|nezvlád)' then return 'J'; end if;
  if p_level ~* '(rozvíj|částeč|s pomocí|s dopomoc|základn)' then return 'C'; end if;
  if p_level ~* '(téměř|skoro|dobře|optimáln)' then return 'T'; end if;
  if p_level ~* '(ovlád|výborn|úplně|zvládl|zvládá|nadstandard|osvojen)' then return 'U'; end if;

  idx := array_position(p_levels, p_level);
  n := coalesce(array_length(p_levels, 1), 0);
  if idx is null or n = 0 then
    return null;
  end if;
  if n = 1 then
    return 'U';
  end if;
  return codes[1 + round((idx - 1) * 3.0 / (n - 1))::int];
end;
$$;

-- The goal's level names in order, from its first criterion.
create or replace function public.goal_level_names(p_goal_id uuid)
returns text[]
language sql
stable
set search_path = public
as $$
  select coalesce(array_agg(ld ->> 'level' order by ord), '{}')
    from (
      select level_descriptors
        from public.evaluation_criteria
       where goal_id = p_goal_id
       order by sort_order, created_at
       limit 1
    ) c,
    jsonb_array_elements(c.level_descriptors) with ordinality as t(ld, ord);
$$;

-- Backfill the new columns from the old ones.
update public.evaluation_criteria
   set teacher_text = description
 where teacher_text is null;

update public.evaluation_criteria c
   set position = r.pos
  from (
    select id, row_number() over (partition by goal_id order by sort_order, created_at) as pos
      from public.evaluation_criteria
  ) r
 where c.id = r.id and c.position is null;

-- Old level descriptions become the scale where every code gets a sentence.
-- A partial mapping (the old three-step scale has no "T") stays null: the scale
-- is regenerated by prompt 03 instead of being half made up.
update public.evaluation_criteria c
   set scale = m.scale
  from (
    select c2.id, jsonb_object_agg(x.code, x.description) as scale
      from public.evaluation_criteria c2
      cross join lateral (
        select distinct on (code) code, description
          from (
            select public.legacy_level_to_jctu(ld ->> 'level', public.goal_level_names(c2.goal_id)) as code,
                   ld ->> 'description' as description,
                   ord
              from jsonb_array_elements(c2.level_descriptors) with ordinality as t(ld, ord)
          ) mapped
         where code is not null and coalesce(btrim(description), '') <> ''
         order by code, ord
      ) x
     group by c2.id
    having count(*) = 4
  ) m
 where c.id = m.id and c.scale is null;

-- Until the old goal editor is replaced, it writes only `description` and
-- `sort_order`. Keep the new columns in step so nothing reads a stale value.
create or replace function public.sync_criterion_legacy_columns()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.teacher_text is null
     or (tg_op = 'UPDATE' and old.description is distinct from new.description
         and old.teacher_text is not distinct from old.description) then
    new.teacher_text := new.description;
  end if;
  if new.position is null then
    new.position := new.sort_order + 1;
  end if;
  return new;
end;
$$;

drop trigger if exists sync_criterion_legacy_columns on public.evaluation_criteria;
create trigger sync_criterion_legacy_columns
  before insert or update on public.evaluation_criteria
  for each row execute function public.sync_criterion_legacy_columns();

-- =============================================================================
-- 3. Exit tickets (one filled-in ticket of one pupil in one lesson)
-- =============================================================================

create table if not exists public.exit_tickets (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references auth.users(id) on delete cascade,
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  source text not null check (source in ('self_qr', 'self_paper')),
  proof_id uuid references public.proofs_of_learning(id) on delete set null,
  pupil_comment text not null default '',
  teacher_comment text not null default '',
  submitted_at timestamptz not null default now(),
  confirmed_by_teacher boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists exit_tickets_lesson_idx on public.exit_tickets (lesson_id);
create index if not exists exit_tickets_student_idx on public.exit_tickets (student_id);

alter table public.exit_tickets enable row level security;

drop policy if exists "Teachers manage own exit tickets" on public.exit_tickets;
create policy "Teachers manage own exit tickets" on public.exit_tickets
  for all
  using (teacher_id = auth.uid())
  with check (
    teacher_id = auth.uid()
    and exists (select 1 from public.students s where s.id = student_id and s.teacher_id = auth.uid())
    and exists (select 1 from public.lessons l where l.id = lesson_id and l.teacher_id = auth.uid())
  );

drop trigger if exists update_exit_tickets_updated_at on public.exit_tickets;
create trigger update_exit_tickets_updated_at
  before update on public.exit_tickets
  for each row execute function public.update_updated_at_column();

-- =============================================================================
-- 4. Criterion assessments: the core of the new version
-- =============================================================================
-- No unique constraint: every entry is a new row and the history is the table.
-- The current level is the latest row per pupil × criterion × source (see the
-- view below).

create table if not exists public.criterion_assessments (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references auth.users(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  criterion_id uuid not null references public.evaluation_criteria(id) on delete cascade,
  level text not null check (level in ('J', 'C', 'T', 'U')),
  source text not null check (source in ('teacher', 'self_qr', 'self_paper')),
  lesson_id uuid references public.lessons(id) on delete set null,
  proof_id uuid references public.proofs_of_learning(id) on delete set null,
  exit_ticket_id uuid references public.exit_tickets(id) on delete cascade,
  assessed_at timestamptz not null default now(),
  confirmed_by_teacher boolean not null default false,
  note text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists criterion_assessments_current_idx
  on public.criterion_assessments (student_id, criterion_id, source, assessed_at desc, created_at desc);
create index if not exists criterion_assessments_criterion_idx on public.criterion_assessments (criterion_id);
create index if not exists criterion_assessments_teacher_idx on public.criterion_assessments (teacher_id);
create index if not exists criterion_assessments_lesson_idx on public.criterion_assessments (lesson_id);
create index if not exists criterion_assessments_exit_ticket_idx on public.criterion_assessments (exit_ticket_id);

alter table public.criterion_assessments enable row level security;

-- A teacher reads and writes only their own rows, and may not attach a level
-- to someone else's pupil or criterion.
drop policy if exists "Teachers manage own criterion assessments" on public.criterion_assessments;
create policy "Teachers manage own criterion assessments" on public.criterion_assessments
  for all
  using (teacher_id = auth.uid())
  with check (
    teacher_id = auth.uid()
    and exists (select 1 from public.students s where s.id = student_id and s.teacher_id = auth.uid())
    and exists (
      select 1
        from public.evaluation_criteria c
        join public.educational_goals g on g.id = c.goal_id
       where c.id = criterion_id and g.teacher_id = auth.uid()
    )
  );

-- Current level per pupil × criterion × source. security_invoker makes the
-- view obey the RLS of the table underneath.
create or replace view public.current_criterion_levels
with (security_invoker = true) as
select distinct on (student_id, criterion_id, source)
       id,
       teacher_id,
       student_id,
       criterion_id,
       source,
       level,
       assessed_at,
       lesson_id,
       proof_id,
       exit_ticket_id,
       confirmed_by_teacher
  from public.criterion_assessments
 order by student_id, criterion_id, source, assessed_at desc, created_at desc;

-- =============================================================================
-- 5. Old goal levels → criterion assessments
-- =============================================================================
-- A goal level applies to every criterion of the goal, with source "teacher".
-- Rows the mapping cannot place are left out; see the preview query in the PR.

insert into public.criterion_assessments
  (teacher_id, student_id, criterion_id, level, source, assessed_at, note)
select sgl.teacher_id,
       sgl.student_id,
       c.id,
       public.legacy_level_to_jctu(sgl.level, public.goal_level_names(sgl.goal_id)),
       'teacher',
       coalesce(sgl.updated_at, sgl.created_at, now()),
       'Převedeno z úrovně cíle: ' || sgl.level
  from public.student_goal_levels sgl
  join public.evaluation_criteria c on c.goal_id = sgl.goal_id
 where public.legacy_level_to_jctu(sgl.level, public.goal_level_names(sgl.goal_id)) is not null
   and not exists (
     select 1 from public.criterion_assessments ca
      where ca.student_id = sgl.student_id
        and ca.criterion_id = c.id
        and ca.note like 'Převedeno z úrovně cíle:%'
   );

-- The capture tool, course overview and dashboard still write goal levels
-- until phase 7 replaces them. Until then every change is mirrored here, so
-- no level is recorded in one place only. Phase 7 drops the old table and
-- this trigger together.
-- Runs as the caller, so the RLS check on criterion_assessments applies: a goal
-- level on someone else's goal cannot turn into a criterion row.
create or replace function public.mirror_goal_level_to_criteria()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  code text;
begin
  if tg_op = 'DELETE' then
    delete from public.criterion_assessments ca
     using public.evaluation_criteria c
     where c.goal_id = old.goal_id
       and ca.criterion_id = c.id
       and ca.student_id = old.student_id
       and ca.source = 'teacher'
       and ca.note like 'Převedeno z úrovně cíle:%';
    return old;
  end if;

  code := public.legacy_level_to_jctu(new.level, public.goal_level_names(new.goal_id));
  if code is not null then
    insert into public.criterion_assessments
      (teacher_id, student_id, criterion_id, level, source, assessed_at, note)
    select new.teacher_id, new.student_id, c.id, code, 'teacher', now(),
           'Převedeno z úrovně cíle: ' || new.level
      from public.evaluation_criteria c
     where c.goal_id = new.goal_id;
  end if;
  return new;
end;
$$;

drop trigger if exists mirror_goal_level_to_criteria on public.student_goal_levels;
create trigger mirror_goal_level_to_criteria
  after insert or delete or update of level on public.student_goal_levels
  for each row execute function public.mirror_goal_level_to_criteria();

-- =============================================================================
-- 6. QR self-assessment sessions
-- =============================================================================
-- A pupil opens /s/:token and writes through api/self-assessment, which uses
-- the service role after checking the token and its validity. There is no
-- public RLS policy: without the endpoint nobody but the teacher gets in.

create table if not exists public.self_assessment_sessions (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references auth.users(id) on delete cascade,
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  -- 64 hex characters from two random UUIDs, no extension needed.
  token text not null unique
    default replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
  expires_at timestamptz not null default (date_trunc('day', now()) + interval '1 day'),
  closed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists self_assessment_sessions_lesson_idx on public.self_assessment_sessions (lesson_id);

alter table public.self_assessment_sessions enable row level security;

drop policy if exists "Teachers manage own self-assessment sessions" on public.self_assessment_sessions;
create policy "Teachers manage own self-assessment sessions" on public.self_assessment_sessions
  for all
  using (teacher_id = auth.uid())
  with check (
    teacher_id = auth.uid()
    and exists (select 1 from public.lessons l where l.id = lesson_id and l.teacher_id = auth.uid())
  );

-- =============================================================================
-- 7. TinyBuddy conversations
-- =============================================================================

create table if not exists public.buddy_conversations (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '',
  -- Page the conversation started from: {lesson_id?, class_id?, student_id?}
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists buddy_conversations_teacher_idx
  on public.buddy_conversations (teacher_id, updated_at desc);

alter table public.buddy_conversations enable row level security;

drop policy if exists "Teachers manage own buddy conversations" on public.buddy_conversations;
create policy "Teachers manage own buddy conversations" on public.buddy_conversations
  for all using (teacher_id = auth.uid()) with check (teacher_id = auth.uid());

drop trigger if exists update_buddy_conversations_updated_at on public.buddy_conversations;
create trigger update_buddy_conversations_updated_at
  before update on public.buddy_conversations
  for each row execute function public.update_updated_at_column();

create table if not exists public.buddy_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.buddy_conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'tool')),
  content text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists buddy_messages_conversation_idx
  on public.buddy_messages (conversation_id, created_at);

alter table public.buddy_messages enable row level security;

drop policy if exists "Teachers manage own buddy messages" on public.buddy_messages;
create policy "Teachers manage own buddy messages" on public.buddy_messages
  for all
  using (exists (
    select 1 from public.buddy_conversations bc
     where bc.id = conversation_id and bc.teacher_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.buddy_conversations bc
     where bc.id = conversation_id and bc.teacher_id = auth.uid()
  ));
